# Generated by Django 3.1.4 on 2020-12-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsair_id', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.BigIntegerField(null=True),
        ),
    ]
