# Generated by Django 3.1.4 on 2020-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsair_id', '0002_auto_20201214_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comp_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
