# Generated by Django 3.1.4 on 2020-12-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsair_id', '0003_auto_20201217_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='comp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
