# Generated by Django 3.1.4 on 2020-12-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsair_id', '0005_auto_20201223_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='views_count',
            new_name='views',
        ),
    ]
