# Generated by Django 3.1.4 on 2021-01-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsair_id', '0009_auto_20210101_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='Jakarta', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='website',
            field=models.URLField(default='', max_length=100),
        ),
    ]
